//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAuthWebApi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Roles
    {
        public int id { get; set; }
        public int User_id { get; set; }
        public int Role_id { get; set; }
    
        public virtual ApiUser ApiUser { get; set; }
        public virtual Role Role { get; set; }
    }
}
